apiVersion: v1
kind: Namespace
metadata:
  name: lab-ncanales
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-ncanales
  namespace: lab-ncanales
  labels:
    app: backend-nest-ncanales
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-ncanales
  template:
    metadata:
      labels:
        app: backend-nest-ncanales
    spec:
      containers:
      - name: backend-ncanales
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-ncanales
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcrednc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ncanales-svc   
  namespace: lab-ncanales
  labels:
    app: backend-ncanales-svc
spec:
  selector:
    app: backend-nest-ncanales
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-ncanales
  namespace: lab-ncanales
spec:
  ingressClassName: nginx
  rules:
  - host: ncanales.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-ncanales-svc
            port:
              number: 80